version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/azureuser/db/:/usr/src/app/src/db/
    env_file: .dockerenvrc
    image:
      - joinakoma/akoma-backend:v1
    ports:
      - "3000:3000"
